### ISSUE TITLE
no element "glvideoflip" error for coral dev board

### ISSUE THREAD

**Issue by mehmandarov** [google-coral/project-posenet#17]
pose_camera.py seems to be failing with:

```
$> python3 pose_camera.py 
Loading model:  models/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite
Detected Edge TPU dev board.
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,framerate=30/1 ! decodebin ! glupload ! glvideoflip video-direction=identity ! tee name=t
               t. ! queue max-size-buffers=1 leaky=downstream ! freezer name=freezer ! glsvgoverlaysink name=overlaysink
               t. ! queue max-size-buffers=1 leaky=downstream ! glfilterbin filter=glbox name=glbox ! video/x-raw,format=RGB,width=641,height=481 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true
            
Traceback (most recent call last):
  File "pose_camera.py", line 163, in <module>
    main()
  File "pose_camera.py", line 159, in main
    run(run_inference, render_overlay)
  File "pose_camera.py", line 124, in run
    jpeg=args.jpeg
  File "<...>/project-posenet/gstreamer.py", line 368, in run_pipeline
    pipeline = GstPipeline(pipeline, inf_callback, render_callback, src_size)
  File "<...>/project-posenet/gstreamer.py", line 42, in __init__
    self.pipeline = Gst.parse_launch(pipeline)
GLib.Error: gst_parse_error: no element "glvideoflip" (1)

```

**Comment by hellsythe** [comment]
i have the same error, any solution?

**Comment by mtyka** [comment]
Are you running Mendel Chef or Mendel Day ? Please be sure to reflash your board with the latest 
Mendel release (Day) from here: https://coral.ai/docs/dev-board/get-started/
I just flashed a clean board and followed those instructions and the pose examples should work out of the box (be also sure to run install_requirements.sh after setting up the board and cloning this repo)

**Comment by mtyka** [comment]
Feel free to reopen this issue if the issue persists.

**Comment by mentarus** [comment]
Same issue, flashed the coral dev board last week with the latest image 5.0 Eagle (Jul 2020)
Isn't install_requirements.sh meant to deal with the dependencies? Definitely not working out of the box...

**Comment by sukhjinder-singh1990** [comment]
hi,  
i got the same error using virtualenv environment on ubuntu 20.04. device used and coral usb 

```
  File "/home/USER/Documents/project-posenet/gstreamer.py", line 42, in __init__
    self.pipeline = Gst.parse_launch(pipeline)
gi.repository.GLib.Error: gst_parse_error: no element "freezer" (1)
```
there is any solution ?
