### ISSUE TITLE
Failed to allocate tensors.

### ISSUE THREAD

**Issue by 12345k** [google-coral/project-posenet#18]
Device: Coral Dev board
After running install_requirements.sh script, I run python3 simple_pose.py and
get different errors.

mendel@bored-horse:~/project-posenet$ python3 simple_pose.py 
--2020-01-31 05:12:31--  https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Hindu_marriage_ceremony_offering.jpg/640px-Hindu_marriage_ceremony_offering.jpg
Resolving upload.wikimedia.org (upload.wikimedia.org)... 103.102.166.240, 2001:df2:e500:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|103.102.166.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83328 (81K) [image/jpeg]
Saving to: ‘couple.jpg’

couple.jpg                                           100%[====================================================================================================================>]  81.38K  --.-KB/s    in 0.1s    

2020-01-31 05:12:32 (841 KB/s) - ‘couple.jpg’ saved [83328/83328]

Traceback (most recent call last):
  File "simple_pose.py", line 25, in <module>
    engine = PoseEngine('models/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite')
  File "/home/mendel/project-posenet/pose_engine.py", line 85, in __init__
    BasicEngine.__init__(self, model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 92, in __init__
    self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
RuntimeError: Internal: Unsupported data type: 1Node number 0 (edgetpu-custom-op) failed to prepare.
Failed to allocate tensors.

**Comment by Namburger** [comment]
@12345k can you share outputs of this command?
```
$  cat /etc/os-release
$ uname -a
$ dpkg -l | grep edgetpu
```
This isn't reproducible for me, I suspecting that maybe you have an outdated system?

**Comment by hjonnala** [comment]
Closing due to inactivity. Feel free to reopen if this issue still persists.
