### ISSUE TITLE
gi.repository.GLib.Error: gst_parse_error: no element "freezer"

### ISSUE THREAD

**Issue by Jaspereclipse** [google-coral/project-posenet#23]
```
(synthesizer.py:3621): GStreamer-WARNING **: 22:02:24.716: Element factory metadata for 'freezer' has no valid long-name field
fluidsynth: warning: Requested a period size of 64, got 444 instead
Loading model:  models/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,width=640,height=480,framerate=30/1 ! decodebin ! videoflip video-direction=identity ! tee name=t
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! freezer name=freezer ! rsvgoverlay name=overlay
                  ! videoconvert ! autovideosink
               t. ! queue max-size-buffers=1 leaky=downstream ! videoconvert ! videoscale ! video/x-raw,width=641,height=480 ! videobox name=box autocrop=true
                  ! video/x-raw,format=RGB,width=641,height=481 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true
            
Traceback (most recent call last):
  File "synthesizer.py", line 155, in <module>
    main()
  File "synthesizer.py", line 151, in main
    pose_camera.run(run_inference, render_overlay)
  File "/home/pi/workspace/project-posenet/pose_camera.py", line 124, in run
    jpeg=args.jpeg
  File "/home/pi/workspace/project-posenet/gstreamer.py", line 368, in run_pipeline
    pipeline = GstPipeline(pipeline, inf_callback, render_callback, src_size)
  File "/home/pi/workspace/project-posenet/gstreamer.py", line 42, in __init__
    self.pipeline = Gst.parse_launch(pipeline)
gi.repository.GLib.Error: gst_parse_error: no element "freezer" (1)
```
I am trying to run this on raspberry pi with edgeTPU but have the above error. How can I fix it?

**Comment by josebagar** [comment]
Hi @Jaspereclipse. I got this same problem when running the code in Fedora 31 and solved it by installing the `python3-gstreamer1` package, so in your case I would double-check that you have installed the required dependencies by running [`install_requirements.sh`](../blob/master/install_requirements.sh).

**Comment by koji** [comment]
Has anyone made this work on mac?

**Comment by hjonnala** [comment]
@koji project-posenet not implemented on Mac yet. 

@Jaspereclipse Please try with latest updates. Feel free to reopen if issue still persists.

**Comment by sukhjinder-singh1990** [comment]
hi,
i got the same error using virtualenv environment on ubuntu 20.04. device used and coral usb 
```

 File "/home/USER/Documents/project-posenet/gstreamer.py", line 365, in run_pipeline
    pipeline = GstPipeline(pipeline, inf_callback, render_callback, src_size)
  File "/home/USER/Documents/project-posenet/gstreamer.py", line 42, in __init__
    self.pipeline = Gst.parse_launch(pipeline)
gi.repository.GLib.Error: gst_parse_error: no element "freezer" (1)
```

any solution ?

**Comment by hyx0329** [comment]
hi @deep-blue33 
> hi, i got the same error using virtualenv environment on ubuntu 20.04. device used and coral usb

in virtual environments, you need to rebuild and install overides of gst-python

this solves my problem, your situration may be different

refs:
- https://github.com/jackersson/gstreamer-python
- http://lifestyletransfer.com/how-to-install-gstreamer-python-bindings/  (see common issues below)

ps. newer gstreamer use meson to build, the old way (using autogen.sh) no longer works
