### ISSUE TITLE
"self._output_offsets" elements should be integers

### ISSUE THREAD

**Issue by ThePersonalDoprano** [google-coral/project-posenet#27]
I'm running the last version of PoseNET on a Google Coral TPU connected to a JetsonNano. 
My Python version is 3.6.9

I'm calling the following function in my code: 
`poses, inference_time = engine.DetectPosesInImage(np.uint8(resized))`
Where `resized` is an image with the following shape: (481, 641, 3)
And i get the following error: 

> Traceback (most recent call last):
  File "/home/gabby/.vscode-server/extensions/ms-python.python-2020.3.71113/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/home/gabby/.vscode-server/extensions/ms-python.python-2020.3.71113/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/gabby/.vscode-server/extensions/ms-python.python-2020.3.71113/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/usr/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gabby/Downloads/project-posenet/testPoint.py", line 584, in <module>
    poses, inference_time = engine.DetectPosesInImage(np.uint8(resized))
  File "/home/gabby/Downloads/project-posenet/pose_engine.py", line 125, in DetectPosesInImage
    return self.ParseOutput(self.run_inference(img.flatten()))
  File "/home/gabby/Downloads/project-posenet/pose_engine.py", line 129, in ParseOutput
    outputs = [output[i:j] for i, j in zip(self._output_offsets, self._output_offsets[1:])]
  File "/home/gabby/Downloads/project-posenet/pose_engine.py", line 129, in <listcomp>
    outputs = [output[i:j] for i, j in zip(self._output_offsets, self._output_offsets[1:])]
TypeError: slice indices must be integers or None or have an __index__ method
Terminated

In this error, in the following function: 
https://github.com/google-coral/project-posenet/blob/da95b4f2724b13d981baa0fdd77cf87745a79f04/pose_engine.py#L127-L129
the array `self.output_offset ` has the following elements: [0, 340.0, 510.0, 520.0, 521.0]
And that array gets its elements from here:
https://github.com/google-coral/project-posenet/blob/da95b4f2724b13d981baa0fdd77cf87745a79f04/pose_engine.py#L101-L103

I solved that error, by casting the elements to integers:
          ` self._output_offsets.append(int(offset))`
And now it works perfectly, and can correctly detect poses.

**Comment by sndroid** [comment]
It seems that there was an automatic cast in adding singed int and unsined int (specifically numpy.uint64) to preserve precision.

**Comment by mtyka** [comment]
Fixed. Thanks for pointing this out !
