### ISSUE TITLE
Error: no module named 'edgetpu'

### ISSUE THREAD

**Issue by Tylersuard** [google-coral/project-posenet#51]
Traceback (most recent call last):
  File "simple_pose.py", line 18, in <module>
    from pose_engine import PoseEngine
  File "/home/pi/coral/tflite/python/examples/project-posenet/pose_engine.py", line 20, in <module>
    from edgetpu import __version__ as edgetpu_version
ModuleNotFoundError: No module named 'edgetpu'

**Comment by Tylersuard** [comment]
Solved: sudo apt-get install python3-edgetpu
