### ISSUE TITLE
Can't run simple_pose.py

### ISSUE THREAD

**Issue by NabilHunt** [google-coral/project-posenet#61]
I installed all requirements and I didn't find any mention of the error I'm having elsewhere, when I run `python3 simple_pose.py`, I get the following error:

```
Traceback (most recent call last):
  File "simple_pose.py", line 27, in <module>
    'models/mobilenet/posenet_mobilenet_v1_075_481_641_quant_decoder_edgetpu.tflite')
  File "/home/pi/tmp/project-posenet/pose_engine.py", line 80, in __init__
    posenet_decoder_delegate = load_delegate(POSENET_SHARED_LIB)
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 81, in __init__
    self._library = ctypes.pydll.LoadLibrary(library)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: posenet_lib/armv7l/posenet_decoder.so: cannot open shared object file: No such file or directory
Exception ignored in: <function Delegate.__del__ at 0xb030d1e0>
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 116, in __del__
    if self._library is not None:
AttributeError: 'Delegate' object has no attribute '_library'
```
I'm not sure what's the problem here, this is being run on a raspberry pi4 with the latest Raspbian. I suspected the issue might be GLIBC version, since mine is `Debian GLIBC 2.28-10+rpi1` and I saw in an issue that it must be 2.29 or higher but the error I got doesn't point to that.

**Comment by Namburger** [comment]
@NabilHunt I think you just need to change the `armv7a` directory from here: https://github.com/google-coral/project-posenet/tree/master/posenet_lib
to `armv7l` since that's what `os.uname().machine` returns. It looked for that directory for the posenet lib and couldn't find it

**Comment by NabilHunt** [comment]
@Namburger seems to be the problem as it's working now after renaming it.
Thanks

I'll close it in a day after I recheck it
