### ISSUE TITLE
How to run the models on CPU?

### ISSUE THREAD

**Issue by i-m-arin** [google-coral/project-posenet#70]
I have installed all the packages described in the readme file but still could not run the models. Is there any way to run the models on the CPU?
This is the error message I got:

Traceback (most recent call last):
  File "/home/arin/anaconda3/envs/evolv_fit/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/home/arin/anaconda3/envs/evolv_fit/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple_pose.py", line 26, in <module>
    engine = PoseEngine(
  File "/home/arin/Documents/companies/Evolv_fit/project-posenet/pose_engine.py", line 79, in __init__
    edgetpu_delegate = load_delegate(EDGETPU_SHARED_LIB)
  File "/home/arin/anaconda3/envs/evolv_fit/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1

**Comment by manoj7410** [comment]
If you see the code at https://github.com/google-coral/project-posenet/blob/master/pose_camera.py#L103 and https://github.com/google-coral/project-posenet/blob/master/pose_engine.py#L79, the model that is being used is specifically meant to run on the edgeTPU only.

**Comment by i-m-arin** [comment]
Thanks, @manoj7410 . Would you please provide a GitHub repo that allows us to run posenet models on CPU with good accuracy(single-pose will be preferred)? It will be very helpful since I am relatively new in this field.

**Comment by manoj7410** [comment]
You should download CPU models from https://coral.ai/models/pose-estimation/#models and try to run these models.

**Comment by i-m-arin** [comment]
Yeah sure. I will try this. Thanks
